geekshop/adminapp/urls.py
from .views import *
from django.urls import path

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', UserCreateView.as_view(), name='user_create'),
    path('users/read/', UserListView.as_view(), name='users'),
    path('users/update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', ProductCategoryListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', ProductCategoryDelete.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/', products, name='products'),
    path('products/read/<int:pk>/', ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', product_update, name='product_update'),
    path('products/delete/<int:pk>/', product_delete, name='product_delete'),
]

geekshop/authapp/urls.py
from django.urls import path
from .views import *

app_name = 'authapp'


urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

geekshop/basketapp/urls.py
from django.urls import path
from .views import *


app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='view'),
    path('add/<int:pk>/', basket_add, name='add'),
    path('remove/<int:pk>/', basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket_edit, name='edit')
,
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, contacts
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admin')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path
from .views import products, product

app_name = 'mainapp'


urlpatterns = [
    path('', products, name='products'),
    path('category/<int:pk>/', products, name='category'),
    path('category/<int:pk>/page/<int:page>/', products, name='page'),
    path('product/<int:pk>/', product, name='product'),
]

geekshop/geekshop/views.py
from django.shortcuts import render


def index(request):
    title = 'Магазин'
    content = {
        'title': title
    }
    return render(request, 'index.html', context=content)

def contacts(request):
    title = 'Контакты'
    content = {
        'title': title
    }
    return render(request, 'contact.html', context=content)

geekshop/geekshop/templates/includes/inc_main_menu.html
<a href="{% url 'index' %}" class="logo"></a>
<ul class="menu">
    <li><a href="{% url 'index' %}"
           class="{% if request.resolver_match.url_name == 'index' %}active{% endif %}">домой</a></li>
    <li><a href="{% url 'mainapp:products' %}"
           class="{% if request.resolver_match.url_name == 'products' %}active{% endif %}">продукты</a></li>
    <li><a href="{% url 'contacts' %}"
           class="{% if request.resolver_match.url_name == 'contacts' %}active{% endif %}">контакты</a></li>


    {% if user.is_authenticated %}
        <li>
            <a href="{% url 'auth:edit' %}">
                {{ user.first_name|default:'Пользователь' }}
            </a>
        </li>
    {% endif %}
    {% if user.is_superuser %}
        <li>
            <a href="{% url 'admin:users' %}">админка</a>
        </li>
    {% endif %}
    <li>
        {% if user.is_authenticated %}
            <a href="{% url 'auth:logout' %}">выйти</a>
        {% else %}
            <a href="{% url 'auth:login' %}">войти</a>
        {% endif %}
    </li>

</ul>
<a href="#" class="search"></a>
<a href="{% url 'basket:view' %}" class="basket">
    <span>
        {% if basket %}{{ basket.0.total_cost|floatformat:0 }}&nbsp;руб({{ basket.0.total_quantity }}шт)
        {% endif %}
    </span>
</a>