geekshop/authapp/urls.py
from django.urls import path
from .views import *

app_name = 'authapp'


urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, contacts
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admin')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

class ShopUser(AbstractUser):
    avatar = models.ImageField(upload_to='users_avatars', blank=True)
    age = models.PositiveIntegerField(verbose_name='возраст')

geekshop/authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms

from .models import ShopUser


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'password1', 'password2', 'email', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data

class ShopUserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'email', 'age', 'avatar', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = ''
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data

geekshop/authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from .forms import ShopUserLoginForm, ShopUserRegisterForm
from django.contrib import auth
from django.urls import reverse


def login(request):
    title = 'вход'

    login_form = ShopUserLoginForm(data=request.POST)

    _next = request.GET['next'] if 'next' in request.GET.keys() else ''

    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            if 'next' in request.POST.keys():
                return HttpResponseRedirect(request.POST['next'])
            else:
                return HttpResponseRedirect(reverse('index'))

    content = {'title': title, 'login_form': login_form, 'next': _next}
    return render(request, 'authapp/login.html', content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    title = 'регистрация'

    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        register_form = ShopUserRegisterForm()

    content = {'title': title, 'register_form': register_form}

    return render(request, 'authapp/register.html', content)


def edit(request):
    return HttpResponseRedirect(reverse('index'))

geekshop/authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="RU">
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}

    {% endblock %}
</head>
<body>
	<div class="container">
        <div class="login">
            <div class="h2 text-center head">
                Вход в систему
            </div>            
            
            {% block content %}

            {% endblock %}
        </div>
	</div>
</body>
</html>   

geekshop/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="mx-auto col-3">
                <form class="form-horizontal" action="{% url 'auth:login' %}" method="post" >
                    {% csrf_token %}
                    {% if next %}
                        <input type="hidden" name="next" value="{{ next }}">
                    {% endif %}
                    {{ login_form.as_p }}
                    <button type="submit" class="btn btn-primary">Войти</button>
                </form>
            </div>
        </div>
        <button class="btn btn-round form-control">
        <a href="{% url 'auth:register' %}" class="">
            зарегистрироваться
        </a>
    </button>
    </div>
{% endblock %}

geekshop/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}
    <form class="form-horizontal" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ register_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="зарегистрироваться">
    </form>
{% endblock %}

geekshop/authapp/templates/authapp/verification.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}

  {% if user %}
    <h3>Поздравляем!</h3>
    <br>
    <h4>Пользователь {{user.username}} подтвержден.</h4>
  {% else %}
    <h3>Верификация не пройдена.</h3>
  {% endif %}
  <br>
  <button class="btn btn-round form-control">
    <a href="{% url 'index' %}" class="">на главную</a>
  </button>

{% endblock %}