geekshop/authapp/urls.py
from django.urls import path
from .views import *

app_name = 'authapp'


urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

geekshop/basketapp/urls.py
from django.urls import path
from .views import *


app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='view'),
    path('add/<int:pk>/', basket_add, name='add'),
    path('remove/<int:pk>/', basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket_edit, name='edit')
,
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, contacts
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admin')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path
from .views import products, product

app_name = 'mainapp'


urlpatterns = [
    path('', products, name='products'),
    path('category/<int:pk>/', products, name='category'),
    path('category/<int:pk>/page/<int:page>/', products, name='page'),
    path('product/<int:pk>/', product, name='product'),
]

geekshop/mainapp/models.py
from django.db import models


# Create your models here.
class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание', blank=True)
    price = models.DecimalField(verbose_name='цена', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

geekshop/mainapp/views.py
import json
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404
from .models import Product, ProductCategory
from basketapp.models import Basket
import random


# Create your views here.
def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_hot_product():
    products = Product.objects.all()
    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]
    return same_products


def products(request, pk=None, page=1):
    title = 'Продукты'
    basket = []
    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
    links_menu = ProductCategory.objects.filter(is_active=True).all()
    products = Product.objects.all()
    if pk is not None:
        if pk == 0:
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
            category = {'name': 'все','pk': 0}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(is_active=True, category__is_active=True, category=pk).order_by('price')

        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            'title': title,
            'links_menu': links_menu,
            'products': products_paginator,
            'category': category,
            'basket': basket,
            'hot_product': hot_product,
            'same_products': same_products,
        }
        return render(request=request, template_name='mainapp/products.html', context=content)
    content = {
        'links_menu': links_menu,
        'title': title,
        'hot_product': hot_product,
        'same_products': same_products,
        'products': products,
        'basket': basket,
    }
    return render(request, 'mainapp/products.html', context=content)


def product(request, pk):
    title = 'продукты'

    content = {
        'title': title,
        'links_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
        'basket': get_basket(request.user),
    }
    return render(request, 'mainapp/product.html', content)

geekshop/mainapp/templates/mainapp/import.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    Import is done
</body>
</html>

geekshop/mainapp/templates/mainapp/product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="hero-white">
            <div class="header clearfix">
                {% include 'includes/inc_main_menu.html' %}
            </div>
        </div>
        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="/media/{{ product.image }}"
                         alt="{{ product.short_desc }}">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#">
                            <img src="/media/{{ product.image }}" alt="вариант 1">
                        </a>
                    </div>
                    <div class="block">
                        <a href="#">
                            <img src="/media/{{ product.image }}" alt="вариант 2">
                        </a>
                    </div>
                    <div class="block">
                        <a href="#">
                            <img src="/media/{{ product.image }}" alt="вариант 3">
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ product.name }}</h3>
                <br>
                <p class="price"> {{ product.price }} <span>руб</span></p>
                <a href="{% url 'basket:add' product.pk %}" class="red-button">
                    заказать
                    <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    {{ product.description }}
                </div>
            </div>
        </div>

    </div>

    <div class="clr"></div>

{% endblock %}

geekshop/mainapp/templates/mainapp/products.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <body>
    <div class="container">
        <div class="hero-white">
            <div class="header clearfix">
                {% include 'includes/inc_main_menu.html' %}
            </div>
        </div>
        <div class="details">
            <div class="links clearfix">
                <ul class="links-menu">
                    <li><a href="{% url 'mainapp:category' 0 %}"
                           class="{% if request.resolver_match.kwargs.pk == 0 %}active{% endif %}">Все</a></li>
                    {% for link in links_menu %}
                        <li><a href="{% url 'mainapp:category' link.id %}"
                               class="{% if request.resolver_match.kwargs.pk|add:'0' == link.id %}active{% endif %}">
                            {{ link.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>

            <div class="details-products">
                <div class="details-slider">
                    <div class="slider-product">
                        <img src="/media/{{ hot_product.image }}">
                    </div>
                    <div class="slider-control">
                        <div class="block">
                            <a href="#"><img src="/media/{{ hot_product.image }}" alt="">
                                <div class="text"></div>
                            </a>
                        </div>
                        <div class="block">
                            <a href="#"><img src="/media/{{ hot_product.image }}" alt="">
                                <div class="text"></div>
                            </a>
                        </div>
                        <div class="block">
                            <a href="#"><img src="/media/{{ hot_product.image }}" alt="">
                                <div class="text"></div>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="description">
                    <h3 class="big-bold">{{ hot_product.name }}</h3>
                    <h3 class="red">горячее предложение</h3>
                    <p class="price"> {{ hot_product.price }} <span>руб</span></p>
                    <a href="{% url 'products:product' hot_product.pk %}" class="red-button">
                        заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                    </a>
                    <div class="description-text">
                        {{ hot_product.description }}
                    </div>
                </div>
            </div>

            <div class="related">
                <div class="title clearfix">
                    <h2>Похожие продукты</h2>
                    <a class="explore" href="#">показать все <img src="{% static 'geekshop/img/arrow.png' %}"
                                                                  alt=""></a>
                </div>

                <div class="related-products clearfix">
                    <div class="paginator">
                        {% if products.has_previous %}
                            <a href="{% url 'products:page' category.pk products.previous_page_number %}">
                                <
                            </a>
                        {% endif %}
                        <span class="current">
				страница {{ products.number }} из
				{{ products.paginator.num_pages }}
			  </span>
                        {% if products.has_next %}
                            <a href="{% url 'products:page' category.pk products.next_page_number %}">
                                >
                            </a>
                        {% endif %}
                    </div>
                    {% for product in products %}
                        <div class="block">
                            <a href="{% url 'products:product' product.pk %}"><img src="/media/{{ product.image }}"
                                                                                   alt="">
                                <div class="text">
                                    <img src="{% static 'geekshop/img/icon-hover.png' %}" alt="img">
                                    <h3>{{ product.category.name }}</h3>
                                    <h4>{{ product.name }}</h4>
                                    <p>{{ product.description }}</p>
                                </div>
                            </a>
                        </div>
                    {% endfor %}


                </div>
            </div>
        </div>

        <div class="clr"></div>

    </div>
{% endblock %}